const API='https://auction-jays-list.vercel.app/api/product-scan';
const el=id=>document.getElementById(id);const setText=(id,v)=>{const x=el(id);if(x)x.textContent=String(v??'—')};const setHidden=(id,v)=>{const x=el(id);if(x)x.hidden=!!v};
function money(v,c='USD'){const n=Number(v);if(!Number.isFinite(n))return'—';try{return new Intl.NumberFormat('en-US',{style:'currency',currency:c||'USD'}).format(n)}catch{return'—'}}
function safeUrl(v){try{const u=new URL(String(v||''));return u.protocol==='https:'?u.toString():null}catch{return null}}
function feature(text){const s=document.createElement('span');s.textContent=String(text);return s}
function renderProduct(p){if(!p)return;setText('shared-product-heading',p.title||'Product identified');setText('shared-product-meta',[p.brand||'Unknown',p.model].filter(Boolean).join(' · '));const list=el('shared-product-features');list?.replaceChildren();for(const x of p.features||[])list?.append(feature(x));const img=el('shared-product-image'),url=safeUrl(p.imageUrl);if(img&&url){img.src=url;img.hidden=false}}
function offerCard(o){const a=document.createElement('article');a.className='offer-card';const h=document.createElement('div');h.className='offer-heading-row';const store=document.createElement('strong');store.textContent=o.store||'Store';const price=document.createElement('strong');price.textContent=money(o.price,o.currency);h.append(store,price);const title=document.createElement('p');title.className='offer-title';title.textContent=o.title||'Same product';a.append(h,title);const url=safeUrl(o.url);if(url){const link=document.createElement('a');link.className='buy-link';link.href=url;link.target='_blank';link.rel='noopener noreferrer';link.textContent='Visit Store';a.append(link)}return a}
function renderResult(r){setHidden('shared-scan-results',false);renderProduct(r.identifiedProduct);const offers=(r.priceComparison||[]).filter(o=>o?.guardianDecision!=='reject'&&safeUrl(o.url));const list=el('shared-comparison-list');list?.replaceChildren();for(const o of offers)list?.append(offerCard(o));if(!offers.length){const p=document.createElement('p');p.textContent='No verified prices found.';list?.append(p)}setText('shared-comparison-count',`${offers.length} offer${offers.length===1?'':'s'}`);const low=r.lowestPrice,url=safeUrl(low?.url);setHidden('shared-lowest-price-card',!low);if(low){setText('shared-lowest-price',money(low.amount,low.currency));setText('shared-lowest-store',low.store||'Store');setText('shared-lowest-details',[low.condition,low.estimatedTotal? `Delivered ${money(low.estimatedTotal,low.currency)}`:null].filter(Boolean).join(' · '));const link=el('shared-lowest-link');if(link&&url){link.href=url;link.hidden=false}}setText('shared-save-amount',r.savings?`Save ${money(r.savings.amount,r.savings.currency)}`:'');const tips=el('shared-savings-tips');tips?.replaceChildren();for(const t of r.savingsTips||[]){const li=document.createElement('li');li.textContent=t;tips?.append(li)}setHidden('shared-savings-card',!(r.savingsTips||[]).length)}
function fileToDataUrl(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||''));r.onerror=reject;r.readAsDataURL(file)})}
let selected=null;
async function choose(file){if(!file||!/^image\/(jpeg|png|webp)$/.test(file.type)){setText('upload-status','Choose a JPG, PNG, or WebP product photo.');return}if(file.size>8*1024*1024){setText('upload-status','Photo must be 8 MB or smaller.');return}selected=file;const data=await fileToDataUrl(file);el('photo-preview').src=data;setText('photo-filename',file.name);setHidden('photo-preview-wrap',false);el('find-price').disabled=false;setText('upload-status','Photo ready.')}
async function search(){if(!selected)return;const btn=el('find-price');btn.disabled=true;setText('upload-status','Identifying product and searching prices…');try{const data=await fileToDataUrl(selected);const payload={action:'product_scan',source:'browser_extension_photo',evidence:{pageTitle:selected.name,title:selected.name.replace(/\.[^.]+$/,''),imageUrl:null,confidence:.2},image:{dataUrl:data,mimeType:selected.type,name:selected.name}};const res=await fetch(API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});if(!res.ok)throw new Error('request failed');const result=await res.json();renderResult(result);setText('upload-status',result.status==='provider_unavailable'?'Product received, but live image/price providers are not connected.':'Search complete.')}catch{setText('upload-status','Auction could not complete this photo search. Please try again.')}finally{btn.disabled=false}}
function start(){const input=el('photo-input'),zone=el('photo-dropzone');zone.addEventListener('click',()=>input.click());input.addEventListener('change',()=>void choose(input.files?.[0]));for(const type of ['dragenter','dragover'])zone.addEventListener(type,e=>{e.preventDefault();zone.classList.add('dragover')});for(const type of ['dragleave','drop'])zone.addEventListener(type,e=>{e.preventDefault();zone.classList.remove('dragover')});zone.addEventListener('drop',e=>void choose(e.dataTransfer?.files?.[0]));el('find-price').addEventListener('click',()=>void search())}
if(typeof document!=='undefined')document.readyState==='loading'?document.addEventListener('DOMContentLoaded',start,{once:true}):start();
