const SCAN_SESSION_REQUEST='AUCTION_SCAN_SESSION_REQUEST',SCAN_SESSION_STATE='AUCTION_SCAN_SESSION_STATE',SHARED_SCAN_RESULT='AUCTION_SHARED_SCAN_RESULT';
const STATE_COPY=Object.freeze({scanning:['Scanning product','Auction is identifying this item.'],identifying:['Identifying product','Auction is checking product evidence.'],searching_stores:['Searching prices','Auction is checking connected online price sources.'],needs_confirmation:['Needs confirmation','Auction needs stronger evidence before calling offers the same product.'],complete:['Prices found','Auction found verified same-product prices.'],partial_results:['Prices found','Auction found prices, but some sources were unavailable.'],no_results:['No cheaper verified price found','The product was identified, but Auction found no safe cheaper exact match.'],provider_unavailable:['Product identified','Live price sources are not available right now.'],error:['Scan unavailable','Auction could not safely complete this scan.']});
const el=id=>document.getElementById(id); const setText=(id,v)=>{const x=el(id);if(x)x.textContent=String(v??'—');}; const setHidden=(id,v)=>{const x=el(id);if(x)x.hidden=!!v;};
function money(v,c='USD'){const n=Number(v);if(!Number.isFinite(n))return'—';try{return new Intl.NumberFormat('en-US',{style:'currency',currency:String(c||'USD').toUpperCase(),minimumFractionDigits:2,maximumFractionDigits:2}).format(n);}catch{return'—';}}
function safeHttpsUrl(v){try{const u=new URL(String(v||''));if(u.protocol!=='https:'||u.username||u.password)return null;u.hash='';return u.toString();}catch{return null;}}
function showState(s){const c=STATE_COPY[s];if(!c)return;setText('panel-title',c[0]);setText('panel-message',c[1]);setText('panel-state',s);}
function renderProduct(p){if(!p)return;setText('shared-product-heading',p.title||'Product identified');setText('shared-product-meta',[p.brand,p.model].filter(Boolean).join(' · ')||'Identity captured');const img=el('shared-product-image'),url=safeHttpsUrl(p.imageUrl);if(img&&url){img.src=url;img.alt=p.title||'Product image';img.hidden=false;}}
function offerCard(o){const card=document.createElement('article');card.className='offer-card shared-offer-card';const head=document.createElement('div');head.className='offer-heading-row';const store=document.createElement('strong');store.textContent=o.store||'Store';const price=document.createElement('strong');price.textContent=money(o.price,o.currency);head.append(store,price);const title=document.createElement('p');title.className='offer-title';title.textContent=o.title||'Verified same product';const detail=document.createElement('p');detail.className='helper-text';detail.textContent=[o.condition,o.shipping==null?'Shipping unknown':`Shipping ${money(o.shipping,o.currency)}`,o.estimatedTotal==null?'Delivered total unavailable':`Delivered ${money(o.estimatedTotal,o.currency)}`].filter(Boolean).join(' · ');card.append(head,title,detail);const url=safeHttpsUrl(o.url);if(url){const a=document.createElement('a');a.className='buy-link';a.href=url;a.target='_blank';a.rel='noopener noreferrer';a.textContent='Visit Store';card.append(a);}return card;}
function renderResult(r){if(!r||typeof r!=='object')return;showState(r.status);renderProduct(r.identifiedProduct);setText('shared-current-price',r.currentPagePrice?money(r.currentPagePrice.amount,r.currentPagePrice.currency):'—');const offers=(Array.isArray(r.priceComparison)?r.priceComparison:[]).filter(o=>o?.guardianDecision!=='reject'&&safeHttpsUrl(o?.url));const list=el('shared-comparison-list');list?.replaceChildren();for(const o of offers)list?.append(offerCard(o));if(!offers.length&&list){const p=document.createElement('p');p.className='helper-text';p.textContent='No verified cheaper prices found yet.';list.append(p);}setText('shared-comparison-count',`${offers.length} offer${offers.length===1?'':'s'}`);const low=r.lowestPrice,url=safeHttpsUrl(low?.url);setHidden('shared-lowest-price-card',!url);if(url){setText('shared-lowest-price',money(low.amount,low.currency));setText('shared-lowest-store',low.store||'Store');setText('shared-lowest-details',[low.condition,low.shipping==null?'Shipping unknown':`Shipping ${money(low.shipping,low.currency)}`,low.estimatedTotal==null?'Delivered total unavailable':`Delivered ${money(low.estimatedTotal,low.currency)}`].filter(Boolean).join(' · '));const a=el('shared-lowest-link');if(a){a.href=url;a.hidden=false;}}setText('shared-save-amount',r.savings?`Save ${money(r.savings.amount,r.savings.currency)}`:'No verified savings yet');const tips=el('shared-savings-tips');tips?.replaceChildren();for(const tip of Array.isArray(r.savingsTips)?r.savingsTips:[]){const li=document.createElement('li');li.textContent=String(tip);tips?.append(li);}setHidden('shared-savings-card',!(r.savingsTips?.length));}
function onMessage(m){if(m?.type===SHARED_SCAN_RESULT)renderResult(m.payload);else if(m?.type===SCAN_SESSION_STATE&&m.payload?.result)renderResult(m.payload.result);}
async function hydrate(){const rt=globalThis.chrome?.runtime;if(!rt?.sendMessage)return;try{const r=await rt.sendMessage({type:SCAN_SESSION_REQUEST});if(r?.type===SCAN_SESSION_STATE&&r.payload?.result)renderResult(r.payload.result);}catch{}}
if(typeof document!=='undefined'&&globalThis.chrome?.runtime){globalThis.chrome.runtime.onMessage?.addListener?.(onMessage);document.addEventListener('DOMContentLoaded',()=>void hydrate(),{once:true});}
